import Head from 'next/head'

const handlerTestPDF = (e) => {
  e.preventDefault()

  const form = new FormData(e.currentTarget)
  const { test } = Object.fromEntries(form)

  if (Number(test) < 1) {
    alert('El número de contenedores debe ser mayor a 0')
    return
  }
  
  fetch('/api/pdfgenerate', {    
    method: 'POST',
    body: JSON.stringify({
      "country": "MEX",
      "numContainers": Number(test),
      "station": "MX5"
    }),
    headers: {
      'Content-Type': 'application/json',      
    }
  }).then(res => res.json())
    .then(({ pdfUrl }) => {
      const base64 = Buffer.from(pdfUrl, 'base64')
      const blob = new Blob([base64], { type: 'application/pdf' })
      const url = window.URL.createObjectURL(blob)
      window.open(url)
  })
  .catch(err => console.log(err))
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>
            Generador de PDF con Next.js y Playwright            
          </h1>          
          <form onSubmit={handlerTestPDF}>            
            <input type="number" name="test" width="100px" defaultValue="1"/>          
            <button>
              Generar PDF PRUEBA
            </button>    
          </form>
        </div>
      </main>
    </>
  )
}
